name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build binaries
        run: |
          # Darwin AMD64
          mkdir -p darwin-amd64
          GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o darwin-amd64/shien ./cmd/shien
          GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o darwin-amd64/shienctl ./cmd/shienctl
          tar -czf shien-darwin-amd64.tar.gz -C darwin-amd64 shien shienctl
          
          # Darwin ARM64
          mkdir -p darwin-arm64
          GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o darwin-arm64/shien ./cmd/shien
          GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o darwin-arm64/shienctl ./cmd/shienctl
          tar -czf shien-darwin-arm64.tar.gz -C darwin-arm64 shien shienctl
          
          # Linux AMD64
          mkdir -p linux-amd64
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o linux-amd64/shien ./cmd/shien
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o linux-amd64/shienctl ./cmd/shienctl
          tar -czf shien-linux-amd64.tar.gz -C linux-amd64 shien shienctl

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            shien-darwin-amd64.tar.gz
            shien-darwin-arm64.tar.gz
            shien-linux-amd64.tar.gz
          generate_release_notes: true