name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build binaries
        run: |
          # Check directory structure
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Go files:"
          find . -name "*.go" -type f | head -10
          
          # Build for macOS AMD64
          echo "Building macOS AMD64..."
          GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o shien-amd64 ./cmd/shien
          GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o shienctl-amd64 ./cmd/shienctl
          tar -czf shien-darwin-amd64.tar.gz shien-amd64 shienctl-amd64
          
          # Build for macOS ARM64
          echo "Building macOS ARM64..."
          GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o shien-arm64 ./cmd/shien
          GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o shienctl-arm64 ./cmd/shienctl
          tar -czf shien-darwin-arm64.tar.gz shien-arm64 shienctl-arm64

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            shien-darwin-amd64.tar.gz
            shien-darwin-arm64.tar.gz
          generate_release_notes: true