name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Build binaries
        run: |
          # Darwin AMD64
          GOOS=darwin GOARCH=amd64 make build-all
          tar -czf shien-darwin-amd64.tar.gz shien shienctl
          
          # Darwin ARM64
          GOOS=darwin GOARCH=arm64 make build-all
          tar -czf shien-darwin-arm64.tar.gz shien shienctl
          
          # Linux AMD64
          GOOS=linux GOARCH=amd64 make build-all
          tar -czf shien-linux-amd64.tar.gz shien shienctl

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            shien-darwin-amd64.tar.gz
            shien-darwin-arm64.tar.gz
            shien-linux-amd64.tar.gz
          generate_release_notes: true