name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-14  # Apple Silicon runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build binaries
        run: |
          echo "Building ARM64 binary with version ${{ steps.get_version.outputs.VERSION }}..."
          VERSION=${{ steps.get_version.outputs.VERSION }} make build-all
          tar -czf shien-darwin-arm64.tar.gz shien-service shien

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            shien-darwin-arm64.tar.gz
          generate_release_notes: true