name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-14  # Apple Silicon runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build binaries
        run: |
          echo "Building ARM64 binary (works on both Apple Silicon and Intel Macs)..."
          go build -ldflags="-s -w" -o shien-service ./cmd/shien-service
          go build -ldflags="-s -w" -o shien ./cmd/shien
          tar -czf shien-darwin-arm64.tar.gz shien-service shien

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            shien-darwin-arm64.tar.gz
          generate_release_notes: true