name: Update Homebrew Formula

on:
  release:
    types: [published]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Get release info
        id: release
        uses: actions/github-script@v7
        with:
          script: |
            const release = context.payload.release;
            const tagName = release.tag_name;
            const tarballUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/archive/refs/tags/${tagName}.tar.gz`;
            
            // Download and calculate SHA256
            const { execSync } = require('child_process');
            execSync(`curl -sL ${tarballUrl} -o /tmp/release.tar.gz`);
            const sha256 = execSync('shasum -a 256 /tmp/release.tar.gz').toString().split(' ')[0];
            
            core.setOutput('version', tagName.replace('v', ''));
            core.setOutput('url', tarballUrl);
            core.setOutput('sha256', sha256);

      - name: Checkout homebrew tap
        uses: actions/checkout@v4
        with:
          repository: reouno/homebrew-shien
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          path: homebrew-tap

      - name: Update Formula
        run: |
          cd homebrew-tap
          sed -i "s|url \".*\"|url \"${{ steps.release.outputs.url }}\"|" Formula/shien.rb
          sed -i "s|sha256 \".*\"|sha256 \"${{ steps.release.outputs.sha256 }}\"|" Formula/shien.rb

      - name: Commit and push
        run: |
          cd homebrew-tap
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Formula/shien.rb
          git commit -m "Update shien to ${{ steps.release.outputs.version }}"
          git push